name: Makefile CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install SDL2
      run: sudo apt-get install -y libsdl2-dev
    - run: ./scripts/build.sh
  test:
    permissions:
      pull-requests: write
      repository-projects: read
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: 'Load testing tools'
      run: sudo gem install ceedling
    - name: 'run tests'
      uses: actions/checkout@v4
      with:
        submodules: true
    - run: ./scripts/test.sh
  analysis:
    permissions: 
      pull-requests: write 
      repository-projects: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: 'Load testing tools'
        run: |
          sudo gem install ceedling
          pip install gcovr
      - name: 'run results process'
        uses: actions/checkout@v4
        with:
          submodules: true
      - run: ./scripts/process_results.sh
      - name: Analysis Comment
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          filePath: ./build/test/process/results.md
          comment_tag: analysis